### ISSUE TITLE
create option to make video recommendations disapper while wathching a video

### ISSUE THREAD

**Issue by OuttaSpaceTime** [wwsalmon/youtube-liberation#17]
I want an option which makes the videos disappear on watching a video:

![image](https://user-images.githubusercontent.com/79710091/125343096-f6f66400-e355-11eb-8d94-73822e7f8fe5.png)

**Comment by wwsalmon** [comment]
fixed in latest version! (pending review in web store, may take a day or two to update) there was a problem with the mobile layout not getting recommendations hidden
